version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_PASSWORD: "${DB_PASS}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$DB_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    ports:
      - 5432:5432

  node:
    image: node:18-alpine
    container_name: node
    environment:
      - NODE_ENV=development
    working_dir: /app
    command: yarn run build:dev
    volumes:
      - ./:/app

volumes:
  postgres_data: