services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  node:
    image: node:18-alpine
    container_name: node
    environment:
      - NODE_ENV=development
    working_dir: /app
    command: yarn run build:dev
    volumes:
      - ./:/app

volumes:
  pgdata: