services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env

  node:
    image: node:18-alpine
    container_name: node
    environment:
      - NODE_ENV=development
    working_dir: /app
    command: yarn run build:dev
    volumes:
      - ./:/app

volumes:
  pgdata: