name: Development Workflow
on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: madalintech/budgetapp:latest

  test:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
    env:
      DJANGO_SETTINGS_MODULE: budgetapp.settings.dev
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEV_DB_NAME: ${{ secrets.DEV_DB_NAME }}
      DEV_DB_USER: ${{ secrets.DEV_DB_USER }}
      DEV_DB_PASS: ${{ secrets.DEV_DB_PASS }}
      DEV_DB_HOST: ${{ secrets.DEV_DB_HOST }}

    services:
      db:
        image: postgres:14
        env:
          POSTGRES_DB: ${{ secrets.DEV_DB_NAME }}
          POSTGRES_USER: ${{ secrets.DEV_DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DEV_DB_PASS }}
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
          cache-dependency-path: |
            **/requirements/*.txt

      - name: Install dependencies
        run: pip install -r requirements/dev.txt

      - name: Make migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate
      - name: Run all unit tests
        run: nox -s test-unit-local
