name: Build

on:
  push:
    branches:
      - dev
      - main

jobs:
  # ==========================================================
  # Build Docker image
  # ==========================================================
  build:
    if: |
      github.ref_name == 'dev' &&
      github.event_name == 'push'
    uses: madalinpopa/budgetapp/.github/workflows/build.yml@dev
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DB_NAME: ${{ secrets.DEV_DB_NAME }}
      DB_USER: ${{ secrets.DEV_DB_USER }}
      DB_PASS: ${{ secrets.DEV_DB_PASS }}
      DB_HOST: ${{ secrets.DEV_DB_HOST }}
  # ==========================================================
  # Run test units
  # ==========================================================
  test:
    needs: build
    if: |
      github.ref_name == 'dev' &&
      github.event_name == 'push'
    uses: madalinpopa/budgetapp/.github/workflows/test.yml@dev
    with:
      test_path: 'tests.unit'
    secrets:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DB_NAME: ${{ secrets.DEV_DB_NAME }}
      DB_USER: ${{ secrets.DEV_DB_USER }}
      DB_PASS: ${{ secrets.DEV_DB_PASS }}
      DB_HOST: ${{ secrets.DEV_DB_HOST }}
