name: Test template

on:
  workflow_call:
    inputs:
      environment:
        default: 'Development'
        required: false
        type: string
      test_path:
        default: 'tests.unit'
        required: false
        type: string
    secrets:
      SECRET_KEY:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      DOCKERHUB_USERNAME:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      DJANGO_SETTINGS_MODULE: ${{ vars.DJANGO_SETTINGS_MODULE }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/budgetbreeze:dev

      - name: Run tests
        run: |
          docker run --rm \
            ${{ secrets.DOCKERHUB_USERNAME }}/budgetbreeze:dev \
            python manage.py test --exclude-tag=integration -v 0
