name: Test template

on:
  workflow_call:
    inputs:
      environment:
        default: 'Development'
        required: false
        type: string
      test_path:
        default: 'tests.unit'
        required: false
        type: string
    secrets:
      SECRET_KEY:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      DJANGO_SETTINGS_MODULE: ${{ vars.DJANGO_SETTINGS_MODULE }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install node packages
        run: yarn install --frozen-lockfile

      - name: Build production static files
        run: yarn run build:prod

      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements/*.txt

      - name: Install dependencies
        run: pip install -r requirements/test.txt

      - name: Make migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Run tests
        run: |
          python manage.py test -v 0 ${{ inputs.test_path }}
